version: '3'

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=bigdata-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - namenode:/hadoop/dfs/name
      - hadoop-config:/opt/hadoop-3.2.1/etc/hadoop
    ports:
      - "9870:9870"
    networks:
      - hadoop-net

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - datanode1:/hadoop/dfs/data
    networks:
      - hadoop-net

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - datanode2:/hadoop/dfs/data
    networks:
      - hadoop-net

  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
    networks:
      - hadoop-net

  spark-worker:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    networks:
      - hadoop-net

  client:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: client
    command: sleep infinity
    volumes:
      - ./data:/data         # Para vehiculos_gps.csv y otros archivos de datos
      - ./scripts:/scripts   # Para tus scripts .py
      - hadoop-config:/opt/hadoop-3.2.1/etc/hadoop  # Configuración compartida
    environment:
      - SPARK_MODE=client
      - CLUSTER_NAME=bigdata-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HADOOP_CONF_DIR=/opt/hadoop-3.2.1/etc/hadoop
    networks:
      - hadoop-net

volumes:
  namenode:
  datanode1:
  datanode2:
  hadoop-config:

networks:
  hadoop-net:
    driver: bridge
